#Given a .pal file with the following format: 64 triplets where each triplet directly corresponds to each of the 64 entries in the NES palette (so first triplet
#represents color for 0x00, second for 0x01 etc. etc.), generate a list (via a txt file) where each index directly corresponds to each entry in the NES palette.

import struct

def main():
    with open("CreateAnims.pal", "rb") as CreateAnimsPal:
        pal = list(CreateAnimsPal.read())
    triplets = [pal[i:i+3] for i in range(0, len(pal), 3)]
    with open("CreateAnimsPalRGBAutoGenerated.txt", "w") as CreateAnimsPalRGBAutoGenerated:
        CreateAnimsPalRGBAutoGenerated.write(f"SYSTEM_PALETTE = [\n")
        for triplet in triplets:
            CreateAnimsPalRGBAutoGenerated.write(f"\t{triplet},\n")
        CreateAnimsPalRGBAutoGenerated.write("]")
main()